#include "UE5_Multi_Shooter/MosesLogChannels.h"

DEFINE_LOG_CATEGORY(LogMosesSpawn);
DEFINE_LOG_CATEGORY(LogMosesMove);
DEFINE_LOG_CATEGORY(LogMosesPickup);
DEFINE_LOG_CATEGORY(LogMosesGAS);
DEFINE_LOG_CATEGORY(LogMosesAI);

DEFINE_LOG_CATEGORY(LogMosesCombat);
DEFINE_LOG_CATEGORY(LogMosesCamera);

DEFINE_LOG_CATEGORY(LogMosesExp);

DEFINE_LOG_CATEGORY(LogMosesPlayer);
DEFINE_LOG_CATEGORY(LogMosesAuth);
DEFINE_LOG_CATEGORY(LogMosesPhase);
DEFINE_LOG_CATEGORY(LogMosesRoom);

DEFINE_LOG_CATEGORY(LogMosesGF);
DEFINE_LOG_CATEGORY(LogMosesHP);
DEFINE_LOG_CATEGORY(LogMosesGrenade);